// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var count, counter, gameContainer, matched, myArray, newArray, numCols, numRows, numTiles, tile, tileCounter, timer, _i, _len, _ref,
      _this = this;

    count = 0;
    counter = setInterval(timer, 1000);
    timer = function() {
      var gameEnd;

      count += 1;
      gameEnd = false;
      if (gameEnd === true) {
        clearInterval(counter);
        return;
      }
      return document.getElmentById("timer").innerHTML = count;
    };
    gameContainer = $('#game');
    numRows = 2;
    numCols = 5;
    numTiles = numRows * numCols;
    myArray = ['A', 'B', 'C', 'D', 'E', 'A', 'B', 'C', 'D', 'E'];
    newArray = shuffle(myArray);
    matched = $('.matched');
    _ref = tileCounter < numTiles;
    for (_i = 0, _len = _ref.length; _i < _len; _i++) {
      tile = _ref[_i];
      tileCounter = 0;
    }
    gameContainer.append(tile)($("<div class='tiles' id=", +(tileCounter + 1), +"> <span class='hidden'>", +newArray[tileCounter], +"</span></div>"));
    return $('.tiles').on('click', function() {
      var revealed;

      revealed = $('.revealed');
      $(_this).children().addClass('revealed');
      if (revealed.length === 0) {
        return console.log($(_this).children().addClass('revealed'));
      } else if (revealed.length) {
        $(_this).children().addClass('revealed');
        if (revealed[0].innerText === $(_this).children().html()) {
          console.log('match checking');
          revealed.addClass('matched');
          console.log(revealed[0]);
          console.log($(_this).children().addClass('matched'));
          revealed.removeClass('revealed');
          $(_this).children().removeClass('revealed');
          revealed.unbind('click');
          return $(_this).children().unbind('click');
        } else {
          console.log('not match');
          if (revealed.length === 2) {
            $(_this).children().removeClass('revealed');
            return revealed.removeClass('revealed');
          }
        }
      }
    });
  });

}).call(this);
