// Generated by CoffeeScript 1.6.2
(function() {
  $(document).ready(function() {
    var count, counter, timer;

    count = 0;
    counter = setInterval(timer, 1000);
    timer = function() {
      var gameEnd;

      count = count + 1;
      gameEnd = false;
      if (gameEnd === true) {
        clearInterval(counter);
      }
    };
    return document.getElementById("timer").innerHTML = count;
  });

}).call(this);
